our_book/books/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^list/$', views.BookListView.as_view(), name='list'),
    url(r'^list/export/csv/$', views.export_all_books_csv, name='export_all_books_csv'),
    url(r'^wish/(?P<year>[0-9]{4})/(?P<month>[0-9]+)/$',
        views.WishBooksMonthArchiveView.as_view(month_format='%m'),
        name='wish_month'),
    url(r'^wish/save/$', views.wish_books_save, name='wish_save'),
    url(r'^wish/(?P<pk>\d+)/cancel/$', views.cancel_wish_book, name='wish_cancel'),
    url(r'^register/$', views.register, name='register'),
    url(r'^register/save/$', views.register_save, name='register_save'),
    url(r'^list/rent/(?P<pk>\d+)/$', views.rent, name='rent'),
    url(r'^return/(?P<pk>\d+)/$', views.return_book, name='return_book'),
    url(r'^search/result/$', views.search_result, name='search_result'),
]

our_book/config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect
from accounts.forms import NewComposeForm
from django_messages.views import *


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^books/', include('books.urls', namespace='books')),
    url(r'^messages/compose/$', compose, {'form_class': NewComposeForm,}, name='messages_compose'),
    url(r'^messages/', include('django_messages.urls')),
    url(r'^$', lambda request: redirect('books:list'), name='index'),  # fixme 차후 메인 페이지로 수정필요
]

# NOTE: serving media files uploaded by a user during development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

our_book/templates/base.html
{% load static %}
{% now "o" as current_year %}{% now "m" as current_month %}

<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>{% block title %}OUR BOOK - 함께 읽는 책{% endblock %}</title>

    <!-- Bootstrap -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- favicon -->
    <link rel="icon" sizes="192x192" href="{% static 'images/logo.png' %}">
    <link rel="apple-touch-icon-precomposed" sizes="180x180"  href="{% static 'images/logo.png' %}">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'index' %}">
                <img alt="Brand" height="20"  src="{% static 'images/logo.png' %}">
            </a>
            <a class="navbar-brand" href="{% url 'index' %}">OUR BOOK</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                        {% block menu %}
                            전체 도서 목록
                        {% endblock %}
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="#">인기도서</a></li>
                        <li><a href="{% url 'books:list' %}">전체 도서 목록</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="{% url 'books:wish_month' current_year current_month%}">도서 구매 신청</a></li>
                        <li><a href="{% url 'books:register' %}">도서 등록</a></li>
                    </ul>
                </li>
            </ul>
            <form class="navbar-form navbar-left" action="{% url 'books:search_result' %}" method="get">
                <div class="form-group">
                    {% block seach_input %}
                        <input type="text" class="form-control" placeholder="Search" name="keyword_list" required>
                    {% endblock %}
                </div>
                <button type="submit" class="btn btn-default">검색</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            {{ user }}<span class="caret"></span>
                            {% if messages_inbox_count %}
                                <span class="text-info">
                                    new
                                </span>
                            {% endif %}
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'profile' user.id %}">회원정보</a></li>
                            <li><a href="{% url 'mybook' %}">도서 대여상황</a></li>
                            <li><a href="{% url 'messages_inbox' %}">
                                쪽지함
                                {% if messages_inbox_count %}
                                    <span class="badge">
                                   {{ messages_inbox_count }}
                                </span>
                                {% endif %}
                            </a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="{% url 'logout' %}">로그아웃</a></li>
                        </ul>
                    </li>
                {% else %}
                    <form class="navbar-form navbar-left" action="{% url 'login' %}" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            {{ login_form }}
                        </div>
                        <button type="submit" class="btn btn-primary">로그인</button>
                        <button type="button" class="btn btn-primary">회원가입</button>
                    </form>

                {% endif %}
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>
<div class="container">
    {% block sidebar %}
    {% endblock %}
    {% block content %}
    {% endblock %}
</div>
<script>
    {% if messages %}
        {% for message in messages %}
            alert("{{ message }}");
        {% endfor %}
    {% endif %}
</script>
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
</body>
</html>