our_book/books/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^list/$', views.BookListView.as_view(), name='list'),
    url(r'^list/export/csv/$', views.export_all_books_csv, name='export_all_books_csv'),
    url(r'^wish/(?P<year>[0-9]{4})/(?P<month>[0-9]+)/$',
        views.WishBooksMonthArchiveView.as_view(month_format='%m'),
        name='wish_month'),
    url(r'^wish/save/$', views.wish_books_save, name='wish_save'),
    url(r'^wish/(?P<pk>\d+)/cancel/$', views.cancel_wish_book, name='wish_cancel'),
    url(r'^register/$', views.register, name='register'),
    url(r'^register/save/$', views.register_save, name='register_save'),
    url(r'^list/rent/(?P<pk>\d+)/$', views.rent, name='rent'),
    url(r'^return/(?P<pk>\d+)/$', views.return_book, name='return_book'),
    url(r'^search/result/$', views.search_result, name='search_result'),
]

our_book/config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect
from accounts.forms import NewComposeForm
from django_messages.views import *


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^books/', include('books.urls', namespace='books')),
    url(r'^messages/compose/$', compose, {'form_class': NewComposeForm,}, name='messages_compose'),
    url(r'^messages/', include('django_messages.urls')),
    url(r'^$', lambda request: redirect('books:list'), name='index'),  # fixme 차후 메인 페이지로 수정필요
]

# NOTE: serving media files uploaded by a user during development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

our_book/books/models.py
from datetime import timedelta, date

from django.core.mail import send_mail
from django.db.models.aggregates import Sum
from django.utils import timezone
from django.conf import settings
from django.db import models
from django.db.models.functions import Coalesce


class Book(models.Model):
    # 도서정보
    title = models.CharField("도서명", max_length=200)
    author = models.CharField("저자", max_length=100)
    publisher = models.CharField("출판사", max_length=100)
    description = models.CharField("책소개", max_length=300, blank=True)
    isbn = models.CharField("ISBN", max_length=25, unique=True)
    isbn13 = models.CharField("ISBN(13자리)", max_length=13, unique=True)
    image = models.URLField("표지이미지", blank=True)
    link = models.URLField("원본링크", blank=True)
    price = models.PositiveIntegerField("가격")
    discount = models.PositiveIntegerField("할인가격", null=True, blank=True)
    pubdate = models.CharField("출판일", max_length=10, blank=True)

    # 추가정보
    created_at = models.DateTimeField("생성일시", auto_now_add=True)
    rent_info = models.OneToOneField('RentHistory', verbose_name='대출정보', blank=True, null=True, related_name='books')

    class Meta:
        ordering = ['-pk']

    def __str__(self):
        return self.title

    # 대여 메소드
    def rent_book(self, user):
        rent_start = date.today()
        rent_end = date.today() + timedelta(days=7)
        rent_info = self.renthistory_set.create(user=user, rent_start=rent_start, rent_end=rent_end, return_status=False)
        self.rent_info=rent_info
        self.save()

    # 반납 메소드
    def return_book(self):
        self.rent_info.return_status=True
        self.rent_info.return_date = date.today()
        self.rent_info.save()  # Q : update로 한번에 처리할 수 없을까?
        self.rent_info=None
        self.save()

    # 연체여부 확인
    def check_overdue(self):
        return self.rent_info.rent_end < date.today()


class RentHistory(models.Model):
    # 대여이력
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='대출회원')
    book = models.ForeignKey(Book, verbose_name='대출도서')
    rent_start = models.DateField("대여시작일")
    rent_end = models.DateField("대여종료일")
    return_status = models.BooleanField("반납여부")
    return_date = models.DateField("반납일", blank=True, null=True)
    sent_overdue_email = models.BooleanField("연체알람여부", default=False)

    def __str__(self):
        return "{}-{}".format(self.user, self.book)

    @property
    def check_overdue(self):
        return self.rent_end < date.today()

    def send_return_info_email(self):
        recipients = self.user
        mail_subject = '[반납안내] {}님 내일은 대출하신 도서의 반납일입니다.({})'.format(recipients.nickname, self.book.title)
        mail_content = '대출도서:{} / 반납예정일:{}'.format(self.book.title, self.rent_end)
        send_mail(mail_subject, mail_content, 'wayhome250@gmail.com', [recipients.email])

    def send_overdue_email(self):
        recipients = self.user
        mail_subject = '[연체안내] {}님 대출도서가 연체되었습니다.({})'.format(recipients.nickname, self.book.title)
        mail_content = '대출도서:{} / 반납예정일:{}'.format(self.book.title, self.rent_end)
        send_mail(mail_subject, mail_content, 'wayhome250@gmail.com', [recipients.email])
        self.sent_overdue_email = True
        self.save()

    @classmethod
    def get_due_date_books(cls):
        return cls.objects.filter(rent_end=date.today()+timedelta(days=1))


class WishBook(models.Model):
    # 도서정보
    title = models.CharField("도서명", max_length=100)
    author = models.CharField("저자", max_length=100)
    publisher = models.CharField("출판사", max_length=100)
    description = models.CharField("책소개", max_length=300, blank=True)
    isbn = models.CharField("ISBN", max_length=50, unique=True)
    isbn13 = models.CharField("ISBN(13자리)", max_length=20, unique=True)
    image = models.URLField("표지이미지", blank=True)
    link = models.URLField("원본링크", blank=True)
    price = models.PositiveIntegerField("가격")
    discount = models.PositiveIntegerField("할인가격", null=True, blank=True)
    pubdate = models.CharField("출판일", max_length=10, blank=True)

    # 추가정보
    created_at = models.DateTimeField("생성일시", auto_now_add=True, db_index=True)
    wish_user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name="구매 신청자", null=True, blank=True)

    class Meta:
        ordering = ['-created_at']

    # 월별 총액
    @classmethod
    def get_total_price(cls, year, month):
        total_price = cls.objects.filter(created_at__year=year, created_at__month=month).aggregate(total=Coalesce(Sum('price'), 0))
        return total_price['total']

    def cancel_wish_book(self):
        self.delete()

our_book/books/forms.py
from django import forms
from .models import Book


class BookForm(forms.ModelForm):
    description = forms.CharField(widget=forms.Textarea)

    class Meta:
        model = Book
        fields = '__all__'

our_book/books/views.py
import csv
import datetime

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models.aggregates import Sum
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.views.decorators.http import require_POST
from django.views.generic.dates import MonthArchiveView
from django.views.generic.list import ListView

from .api import get_book_info, register_book
from .models import Book, WishBook
from utils.slack import slack_notify


class BookListView(ListView):
    model = Book
    paginate_by = 10
    context_object_name = 'books'


def export_all_books_csv(request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="books.csv"'

    writer = csv.writer(response)
    fields = [field.name for field in Book._meta.fields if field.name not in ['rent_info']]
    writer.writerow(fields)
    books = Book.objects.all().values_list(*fields)

    for book in books:
        writer.writerow(book)

    return response


class WishBooksMonthArchiveView(MonthArchiveView):
    model = WishBook
    date_field = "created_at"
    context_object_name = 'wish_books'
    allow_empty = True

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        year = self.kwargs['year']
        month = self.kwargs['month']
        context['total_price'] = WishBook.get_total_price(year, month)
        return context


@login_required
def wish_books_save(request):
    if request.method == 'POST':
        isbn = request.POST['isbn']
        message, book = register_book(isbn, model=WishBook)
        messages.info(request, message)
        if book:
            book.wish_user = request.user
            book.save()
    return redirect('books:wish_month', year=datetime.datetime.today().year, month=datetime.datetime.today().month)


@login_required
def cancel_wish_book(request, pk):
    wish_book = get_object_or_404(WishBook, pk=pk)
    if request.user == wish_book.wish_user and wish_book.created_at.month == datetime.datetime.today().month:
        wish_book.cancel_wish_book()
        messages.info(request, '구매 희망도서를 취소했습니다.')
    else:
        messages.warning(request, '잘못된 접근입니다. 지난달 구매신청을 취소하시려면 관리자에게 문의하세요.')
    return redirect('books:wish_month', year=datetime.datetime.today().year, month=datetime.datetime.today().month)


def register(request):
    return render(request, 'books/register.html')


@require_POST
def register_save(request):
    isbn = request.POST['isbn']
    message, book = register_book(isbn)
    messages.info(request, message)
    if book:
        attachments = [{
            "color": "#36a64f",
            "title": "신규도서",
            "title_link": "http://127.0.0.1:7000/books/list/",
            "fallback": "신규도서 알림",
            "text": "{}".format(book.title)
        }]
        slack_notify(channel='#new_book', username='새책 알림봇', attachments=attachments)
    return redirect('books:register')


@login_required
def rent(request, pk):
    if request.method == 'POST':
        book = get_object_or_404(Book, pk=pk)
        book.rent_book(request.user)
        messages.info(request, '대여성공! 반납 예정일은 {} 입니다.'.format(book.rent_info.rent_end))
        return redirect('mybook')
    else:
        return redirect('books:list')


@login_required
@require_POST
def return_book(request, pk):
    book = get_object_or_404(Book, pk=pk)
    if book.rent_info.user == request.user:
        book.return_book()
        messages.info(request, '반납성공!')
        slack_notify("[도서반납] {}".format(book.title), '#return_book', username='반납 알림봇')
    else:
        messages.error(request, '문제가 발생했습니다.')
    return redirect('mybook')


def search_result(request):
    if request.GET.get('keyword_list'): # note: 찾는 Key가 없으면 default 값 리턴 (None), KeyError 발생 방지
        keyword = request.GET['keyword_list']
        books = Book.objects.filter(title__icontains=keyword)
        return render(request, 'books/book_list.html', {'books': books})

    if request.GET.get('keyword_wish'):
        keyword = request.GET['keyword_wish']
        books = get_book_info(keyword, display='5')
        return render(request, 'books/wish_book.html', {'books': books})

    if request.GET.get('keyword_register'):
        keyword = request.GET['keyword_register']
        books = get_book_info(keyword, display='5')
        return render(request, 'books/register.html', {'books': books})

    messages.warning(request, '검색어를 입력해주세요.')
    return redirect('books:list')

our_book/templates/books/book_list.html
{% extends "base.html"  %}


{% block title %}OUR BOOK - 전체 도서{% endblock %}

{% block content %}
    {% if books %}
        <h2>사내도서 전체목록 (총 {{ paginator.count }}권)</h2>
        <p>사내 도서를 검색하고 대여신청(7일)을 할 수 있어요. <a href="{% url 'books:export_all_books_csv' %}">(전체도서 csv 다운로드)</a></p>
        {% if is_paginated %}
            <ul class="pagination pagination-book-list">
                {% if page_obj.has_previous %}
                    <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
                {% else %}
                    <li class="disabled"><span>&laquo;</span></li>
                {% endif %}
                {% for i in paginator.page_range %}
                    {% if page_obj.number == i %}
                        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                    {% else %}
                        <li><a href="?page={{ i }}">{{ i }}</a></li>
                    {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                    <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
                {% else %}
                    <li class="disabled"><span>&raquo;</span></li>
                {% endif %}
            </ul>
        {% endif %}
        {% for book in books %}
            {% include 'include/book.html' with type='list' %}
        {% endfor %}
    {% else %}
        <h2>찾으시는 도서가 없습니다.</h2>
        <h4><a href="{% url 'books:wish_month' current_year current_month%}">도서 구매신청</a> 메뉴를 통해서 원하는 책을 신청할 수 있어요! :)
            <br><a href="{% url 'books:list' %}">전체 도서 목록</a> 보러가기</h4>
    {% endif %}
{% endblock %}

our_book/templates/books/register.html
{% extends "base.html"  %}


{% block title %}OUR BOOK - 신규도서등록{% endblock %}

{% block menu %}도서 등록{% endblock %}

{% block seach_input %}
    <input type="text" class="form-control" placeholder="Search" name="keyword_register">
{% endblock %}

{% block content %}
    {% if books %}
        <h2>검색 결과</h2>
        <h4>구매한 신규 도서를 등록합니다.</h4>
        {% for book in books %}
            {% include 'include/book.html' with type='register' %}
        {% endfor %}
    {% else %}
        <h2>도서 등록</h2>
        <p>새롭게 구매한 책을 검색하고, 도서 목록에 등록합니다.</p>
        <form class="" action="{% url 'books:search_result' %}" method="get">
            <div class="form-group">
                <input type="text" class="body-search-input form-control input-lg" placeholder="Search" name="keyword_register">
            </div>
        </form>
    {% endif %}

{% endblock %}

our_book/templates/books/wish_book.html
{% extends "base.html"  %}
{% load humanize %}

{% block title %}OUR BOOK - 도서구매신청{% endblock %}

{% block menu %}도서 구매 신청{% endblock %}

{% block seach_input %}
    <input type="text" class="form-control" placeholder="Search" name="keyword_wish" required>
{% endblock %}

{% block content %}
    <h2>검색 결과</h2>
    <h4>희망 도서를 구매 요청 할 수 있습니다 <a href="{% url 'books:wish_month' current_year current_month%}">도서구매 신청 현황</a></h4>
    <form action="{% url 'books:search_result' %}" method="get">
        <div class="form-group">
            <input type="text" class="body-search-input form-control input-lg" placeholder="Search" name="keyword_wish">
        </div>
    </form>
    {% for book in books %}
        {% include 'include/book.html' with type='wish'%}
    {% endfor %}
{% endblock %}

our_book/templates/books/wishbook_archive_month.html
{% extends "base.html"  %}
{% load humanize %}

{% block title %}OUR BOOK - 도서구매신청{% endblock %}

{% block menu %}도서 구매 신청{% endblock %}

{% block seach_input %}
    <input type="text" class="form-control" placeholder="Search" name="keyword_wish" required>
{% endblock %}

{% block content %}
    {% if books %}
        <h2>검색 결과</h2>
        <h4>희망 도서를 구매 요청 할 수 있습니다 <a href="{% url 'books:wish_month' current_year current_month%}">도서구매 신청 현황</a></h4>
        <form action="{% url 'books:search_result' %}" method="get">
            <div class="form-group">
                <input type="text" class="body-search-input form-control input-lg" placeholder="Search" name="keyword_wish">
            </div>
        </form>
        {% for book in books %}
            {% include 'include/book.html' with type='wish'%}
        {% endfor %}
    {% else %}
        <h2>희망 도서 신청</h2>
        <h4>구매를 희망하는 도서를 검색하고, 구매 신청을 진행합니다.</h4>
        <form action="{% url 'books:search_result' %}" method="get">
            <div class="form-group">
                <input type="text" class="body-search-input form-control input-lg" placeholder="Search" name="keyword_wish">
            </div>
        </form>
        <hr>
        <h2>{{ month|date:"o년 b" }} 희망도서 신청 이력 ({{ wish_books.count }}권)</h2>
        <p>구매 가능 총 금액 : <code>300,000원</code> / 구매 신청 누적금액 : <code>{{ total_price|intcomma }}원</code><br>구매 가능 금액은 <u>매달 1일</u> 갱신됩니다. </p>
        <p>
        <ul class="pager">
            {% if previous_month %}
                <li class="previous"><a href="{% url 'books:wish_month' previous_month|date:"o" previous_month|date:"m" %}">&larr; {{ previous_month|date:"o년 b" }}</a></li>
            {% else %}
                <li class="previous disabled"><a href="#">&larr; Older</a></li>
            {% endif %}
            <li><a href="{% url 'books:wish_month' current_year current_month%}">{% now "o년 b" %}</a></li>
            {% if next_month %}
                <li class="next"><a href="{% url 'books:wish_month' next_month|date:"o" next_month|date:"m" %}">{{ next_month|date:"o년 b" }} &rarr;</a></li>
            {% else %}
                <li class="next disabled"><a href="#">Newer &rarr;</a></li>
            {% endif %}
        </ul>
        {% for book in wish_books %}
            {% include 'include/book.html' with type='wish_save'%}
        {% endfor %}
    {% endif %}

{% endblock %}